[package]
name = "dogeos-reth-txpool"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
derive_more.workspace = true
dogeos-protocol-types = { workspace = true, features = ["std"] }
dogeos-reth-primitives = { workspace = true, features = ["std", "reth-codec"] }
dogeos-hardforks = { workspace = true, features = ["std"] }
dogeos-reth-evm = { workspace = true, features = ["std"] }
parking_lot.workspace = true
reth-chainspec = { workspace = true, features = ["std"] }
reth-evm.workspace = true
reth-primitives-traits = { workspace = true, features = ["std"] }
reth-revm.workspace = true
reth-storage-api = { workspace = true, features = ["std"] }
reth-storage-errors.workspace = true
reth-transaction-pool.workspace = true
revm-scroll.workspace = true
thiserror.workspace = true
tracing.workspace = true

[features]
default = ["std"]
std = []

[dev-dependencies]
dogeos-chainspec = { workspace = true, features = ["std"] }
dogeos-reth-primitives = { workspace = true, features = ["serde"] }
reth-provider = { workspace = true, features = ["test-utils"] }
