[package]
name = "dogeos-reth-node"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
dogeos-chainspec = { workspace = true, features = ["std"] }
dogeos-reth-engine = { workspace = true, features = ["std"] }
dogeos-reth-primitives = { workspace = true, features = ["std", "serde", "reth-codec"] }
reth-ethereum = { workspace = true, features = ["node"] }
reth-node-types.workspace = true
