[package]
name = "dogeos-reth-node"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
dogeos-chainspec = { workspace = true, features = ["std"] }
dogeos-reth-engine = { workspace = true, features = ["std"] }
dogeos-reth-consensus = { workspace = true, features = ["std"] }
dogeos-reth-evm = { workspace = true, features = ["std"] }
dogeos-reth-payload = { workspace = true, features = ["std"] }
dogeos-reth-txpool = { workspace = true, features = ["std"] }
dogeos-reth-primitives = { workspace = true, features = ["std", "serde", "reth-codec"] }
eyre.workspace = true
reth-evm.workspace = true
reth-node-builder.workspace = true
reth-node-types.workspace = true
reth-network.workspace = true
reth-provider.workspace = true
reth-primitives-traits.workspace = true
reth-storage-api = { workspace = true, features = ["std", "db-api"] }
reth-transaction-pool.workspace = true
tracing.workspace = true

[dev-dependencies]
reth-consensus.workspace = true
