[package]
name = "dogeos-reth-evm"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-evm = { workspace = true, features = ["rpc"] }
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, optional = true }
auto_impl.workspace = true
derive_more.workspace = true
dogeos-chainspec.workspace = true
dogeos-hardforks.workspace = true
dogeos-protocol-types.workspace = true
dogeos-reth-primitives = { workspace = true, optional = true }
encoder-standard = { workspace = true, optional = true }
reth-evm = { workspace = true, optional = true }
reth-execution-types = { workspace = true, optional = true }
reth-chainspec.workspace = true
reth-primitives-traits = { workspace = true, optional = true }
reth-storage-errors = { workspace = true, optional = true }
revm = { workspace = true, features = ["optional_no_base_fee"] }
revm-scroll.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
eyre.workspace = true

[features]
default = ["std"]
std = [
    "alloy-consensus/std",
    "alloy-eips/std",
    "alloy-evm/std",
    "alloy-primitives/std",
    "dep:alloy-rpc-types-engine",
    "alloy-rpc-types-engine/std",
    "dogeos-protocol-types/std",
    "dogeos-protocol-types/k256",
    "dogeos-chainspec/std",
    "dogeos-hardforks/std",
    "dep:dogeos-reth-primitives",
    "dogeos-reth-primitives/std",
    "dep:reth-evm",
    "reth-evm/std",
    "dep:reth-execution-types",
    "reth-execution-types/std",
    "reth-chainspec/std",
    "dep:reth-primitives-traits",
    "reth-primitives-traits/std",
    "dep:reth-storage-errors",
    "reth-storage-errors/std",
    "revm/std",
    "revm-scroll/std",
    "serde?/std",
    "zstd_compression",
]
serde = [
    "dep:serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "dogeos-protocol-types/serde",
    "revm/serde",
    "revm-scroll/serde",
]
zstd_compression = ["dep:encoder-standard"]
