[package]
name = "dogeos-reth-consensus"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
alloy-consensus.workspace = true
alloy-primitives.workspace = true
dogeos-chainspec.workspace = true
dogeos-hardforks.workspace = true
dogeos-protocol-types = { workspace = true, features = ["std"] }
dogeos-reth-primitives = { workspace = true, features = ["std", "reth-codec"] }
reth-consensus.workspace = true
reth-consensus-common.workspace = true
reth-execution-types.workspace = true
reth-primitives-traits = { workspace = true, features = ["std"] }
thiserror.workspace = true

[features]
default = ["std"]
std = ["dogeos-chainspec/std", "dogeos-hardforks/std"]
